Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ecommerce.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;

namespace ecommerce.Controllers
{
    public class CustomerController : Controller
    {
        private CommerceContext _context;
    
        public CustomerController(CommerceContext context)
        {
            _context = context;
        }

        [HttpGet]
        [Route("customers")]
        public IActionResult Customers()
        {
            ViewBag.AllCustomers = _context.Customers.OrderByDescending(d => d.CreatedAt).ToList();
            return View();
        }

        [HttpPost]
        [Route("customer/add")]
        public IActionResult AddCustomer(Customer customer)
        {
            if(ModelState.IsValid)
            {
                List<Customer> AllCustomers = _context.Customers.ToList();
                if(AllCustomers.Exists(c => c.Name == customer.Name))
                {
                    TempData["customer"] = "That customer already exists";
                }
                else
                {
                    _context.Add(customer);
                    _context.SaveChanges();                    
                }
            }
            TempData["customer"] = "Invalid customer input";
            return RedirectToAction("Customers");
        }

        [HttpGet]
        [Route("customer/delete/{customerid}")]
        public IActionResult Delete(int customerid)
        {
            Customer CustDel = _context.Customers.SingleOrDefault(c => c.CustomerId == customerid);
            _context.Customers.Remove(CustDel);
            _context.SaveChanges();
            return RedirectToAction("Customers");
        }


    }
}

Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ecommerce.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Stripe;

namespace ecommerce.Controllers
{
    public class OrderController : Controller
    {
        private CommerceContext _context;
    
        public OrderController(CommerceContext context)
        {
            _context = context;
        }

        [HttpGet]
        [Route("orders")]
        public IActionResult Orders()
        {
            List<Order> AllOrders = _context.Orders.OrderByDescending(d => d.CreatedAt).Include(c => c.Customer).Include(p => p.Product).ToList();
            List<Product> AllProducts = _context.Products.OrderByDescending(d => d.CreatedAt).ToList();
            List<Customer> AllCustomers = _context.Customers.OrderByDescending(d => d.CreatedAt).ToList();
            ViewBag.AllOrders = AllOrders;            
            ViewBag.AllProducts = AllProducts;
            ViewBag.AllCustomers = AllCustomers;
            return View();
        }

        [HttpPost]
        [Route("order/add")]
        public IActionResult AddOrder(Order order)
        {
            if(ModelState.IsValid)
            {
                Product product = _context.Products.SingleOrDefault(p => p.ProductId == order.ProductId);
                if(product.Stock - order.Quantity < 0)
                {
                    TempData["stock"] = "There is not enough stock to make this order";
                }
                else
                {
                    _context.Add(order);
                    product.Stock = product.Stock - order.Quantity;
                    product.UpdatedAt = DateTime.Now;
                    _context.SaveChanges();
                }
            }
            return RedirectToAction("Orders");
        }

        [HttpPost]
        [Route("Order/Charge/{productid}")]
        public IActionResult Charge(string  stripeEmail, string stripeToken, int productid)
        {
            var customers = new StripeCustomerService();
            var charges = new StripeChargeService();

            var customer = customers.Create(new StripeCustomerCreateOptions {
            Email = stripeEmail,
            SourceToken = stripeToken
            });
            Product product = _context.Products.SingleOrDefault(p => p.ProductId == productid);
            var charge = charges.Create(new StripeChargeCreateOptions {
            Amount = (int)product.Price*100,
            Description = "Sample Charge",
            Currency = "usd",
            CustomerId = customer.Id
            });

            List<Order> AllOrders = _context.Orders.OrderByDescending(d => d.CreatedAt).Include(c => c.Customer).Include(p => p.Product).ToList();
            List<Product> AllProducts = _context.Products.OrderByDescending(d => d.CreatedAt).ToList();
            List<Customer> AllCustomers = _context.Customers.OrderByDescending(d => d.CreatedAt).ToList();
            ViewBag.AllOrders = AllOrders;            
            ViewBag.AllProducts = AllProducts;
            ViewBag.AllCustomers = AllCustomers;

            return View("Orders");
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ecommerce.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;

namespace ecommerce.Controllers
{
    public class ProductController : Controller
    {
        private CommerceContext _context;
    
        public ProductController(CommerceContext context)
        {
            _context = context;
        }

        [HttpGet]
        [Route("products")]
        public IActionResult Products()
        {
            ViewBag.AllProducts = _context.Products.OrderByDescending(d => d.UpdatedAt).ToList();
            return View();
        }

        [HttpPost]
        [Route("product/add")]
        public IActionResult AddProduct(Product product)
        {
            if(ModelState.IsValid)
            {
                _context.Add(product);
                _context.SaveChanges();
                return RedirectToAction("Products");
            }
            return RedirectToAction("Products");
        }

    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ecommerce</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">ecommerce</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Dashboard</a></li>
                    <li><a asp-area="" asp-controller="Product" asp-action="Products">Products</a></li>
                    <li><a asp-area="" asp-controller="Order" asp-action="Orders">Orders</a></li>
                    <li><a asp-area="" asp-controller="Customer" asp-action="Customers">Customers</a></li>
                    <li><a href"/">Settings</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - ecommerce</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>